feat: add free first mint guide
thirdweb-dev/docs pull request #187
Opened 2022-07-25 14:34 UTC by avneesh0612

2022-07-26 06:35 UTC, jarrodwatts requested changes

2022-07-26 06:35 UTC, jarrodwatts commented on guides/free-first-mint/index.mdx
> +Now to get the base id, go to the [Airtable API](https://airtable.com/api) and click on the base that you just created.
This isn't clear to me, can you add an image of where to find this?

2022-07-26 13:12 UTC, avneesh0612 commented on guides/free-first-mint/index.mdx
> +Now to get the base id, go to the [Airtable API](https://airtable.com/api) and click on the base that you just created.
fixed it

2022-08-10 20:55 UTC, nachoiacovino commented on guides/simultaneous-allowlists/index.mdx
>  date: "2022-07-19"
```suggestion
date: "2022-08-10"
```

2022-09-12 11:00 UTC, closed without merging