update guide from randomized to shuffle NFT drop
thirdweb-dev/docs pull request #199
Opened 2022-07-27 21:54 UTC by warengonzaga

hey there!

- remove the old guide (Deploy a randomized NFT drop without writing any code)
- add a new version of the guide (How to shuffle your NFT drop without writing any code)
- completely from scratch guide from the latest UI/UX

@nachoiacovino kindly review
@rattrayd11 kindly prepare a new thumbnail for the guide

Cheers! 🎉

2022-07-27 22:08 UTC, warengonzaga commented
Thanks, @rattrayd11 for the thumbnail! LFG!

2022-07-28 14:33 UTC, nachoiacovino requested changes
Small things and let's ship it

2022-07-28 14:33 UTC, nachoiacovino commented on guides/shuffle-nft-drop/index.mdx
> +# How to shuffle your NFT drop without writing any code
Remove "How to"

2022-07-28 14:33 UTC, nachoiacovino commented on guides/shuffle-nft-drop/index.mdx
> +In this guide, we’ll [deploy a collection using the NFT drop contract](https://portal.thirdweb.com/guides/release-an-nft-drop-with-no-code), after that, we'll **batch upload** it to the dashboard and
Internal links should not have portal.thirdweb.com in front, they should start with /. In this case /guides/release...

2022-07-28 14:33 UTC, nachoiacovino commented on guides/shuffle-nft-drop/index.mdx
> +Let’s assume you’ve already a MetaMask wallet, if not please follow our [create a MetaMask wallet tutorial](https://portal.thirdweb.com/guides/create-a-metamask-wallet).
Same thing here

2022-07-28 14:33 UTC, nachoiacovino commented on guides/shuffle-nft-drop/index.mdx
> +- Minting will still follow the order of token ID.
"Minting will still be sequential by token ID"

2022-07-28 15:46 UTC, warengonzaga commented on guides/shuffle-nft-drop/index.mdx
> +In this guide, we’ll [deploy a collection using the NFT drop contract](https://portal.thirdweb.com/guides/release-an-nft-drop-with-no-code), after that, we'll **batch upload** it to the dashboard and
replaced all the links. 💪

2022-07-28 15:47 UTC, warengonzaga commented on guides/shuffle-nft-drop/index.mdx
> +- Minting will still follow the order of token ID.
Done, thanks!

2022-07-28 15:47 UTC, warengonzaga commented
Done with the requested changes @nachoiacovino 💪

2022-07-28 16:59 UTC, nachoiacovino approved these changes
lgtm!

2022-08-18 23:14 UTC, merged