magic guide
thirdweb-dev/docs pull request #42
Opened 2022-05-12 13:50 UTC by razacodespython

2022-05-12 18:21 UTC, jnsdls requested changes
please update this @razacodespython

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +Note prior to starting to build the app, make sure you have a Magic link account setup. Click [here](https://magic.link) to create one.
according to @palerthanale we should not use click "here" links. google finds these spammy.

Instead just link the thing you're referring to correctly. So in this case probably `Magic link account` should be the linked part.

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +```html
this cannot be `html` because it uses react-props on the `input` component, so `jsx` or `tsx` would be more appropriate here

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +```html
again, can't be `html`

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +	const [email, setEmail] = useState<string>("");
ideally we remove the (very little) types that this has, it's easier to just keep it as javascript. people can follow along more easily:
```suggestion
```jsx
//inside your app
const Home = () => {
	const [email, setEmail] = useState("");
```

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +...
barely any useful types, let's make it jsx instead
```suggestion
```jsx
import { useAddress, useDisconnect, useMagic } from "@thirdweb-dev/react";

//inside your app
const Home = () => {
	const connectWithMagic = useMagic(); // Hook to connect with Magic Link.
...
```

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +      walletConnectors={connectors}
we never set up the `connectors` array here, so this might be confusing?

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +};
much more digestible if we just adjust it

```suggestion
```jsx
const magicLinkConnectorOptions = {
  name: "magic",
  options: {
    // Replace this with your own magic link api key
    apiKey: "pk_live_3B2498906537FF2A"
  },
};
```

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +    },
we do not need rpcUrls to be passed into the options here, this is all set up for the user under the hood, the only required option is the apiKey

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +In the `_app.tsx` file we need to include a connection for Magic link. To do this we use the `WalletConnector` provided by thirdweb’s `React` sdk. Note you also need to pass your api key from your Ma
Keep it less next-js (with typescript) specific imo...

```suggestion
In the root of our application we need to include the options for the Magic Link connector. The only required option for the magic link connector is your magic link `api key` which you will be able to find in your magic link dashboard.
```

2022-05-12 18:21 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +Inside your wrapper make sure to include a reference to the connector.
```suggestion
Make sure to pass the magic link connector option to the `<ThirdwebProvider />` `walletConnectors` prop.
```

... and then show below how we're passing the exact key we defined above into an array with the connectors

2022-05-13 06:15 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +    },
@jarrodwatts showed me that the react SDK requires this right now, I'll make sure it doesn't going forward

2022-05-13 06:18 UTC, jnsdls commented on guides/create-magic-wallet/index.mdx
> +Check out the full file [here](https://github.com/thirdweb-example/magic-link-next-ts/blob/main/pages/_app.tsx).
```suggestion
Check out the [full file](https://github.com/thirdweb-example/magic-link-next-ts/blob/main/pages/_app.tsx).
```

2022-05-17 06:06 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +date: "2022-05-12"
done

2022-05-17 06:07 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +Note prior to starting to build the app, make sure you have a Magic link account setup. Click [here](https://magic.link) to create one.
done

2022-05-17 06:08 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +Go ahead and clone [this](https://github.com/thirdweb-example/next-typescript-starter) repo to get the starters template. We will go through the logic, but won't show every piece of code. If you want
done

2022-05-17 06:11 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +    },
ok

2022-05-17 06:12 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +    apiKey: "pk_live_3B2498906537FF2A",
changed it to send that message

2022-05-17 06:16 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +```html
adjusted

2022-05-17 06:16 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +};
done

2022-05-17 06:16 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +In the `_app.tsx` file we need to include a connection for Magic link. To do this we use the `WalletConnector` provided by thirdweb’s `React` sdk. Note you also need to pass your api key from your Ma
done

2022-05-17 06:17 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +Inside your wrapper make sure to include a reference to the connector.
done

2022-05-17 06:21 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +Check out the full file [here](https://github.com/thirdweb-example/magic-link-next-ts/blob/main/pages/_app.tsx).
done

2022-05-17 08:09 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +That’s how you build a functionality that lets the user login with their email address. Again we went over the core logic of the app. Feel free to go to the repo to get a full copy and start using th
done

2022-05-17 08:10 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +	const [email, setEmail] = useState<string>("");
ok

2022-05-17 08:11 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +```tsx
done

2022-05-17 08:11 UTC, razacodespython commented on guides/create-magic-wallet/index.mdx
> +...
done

2022-05-18 00:14 UTC, jnsdls approved these changes

2022-05-18 00:26 UTC, merged