add useNetwork hook
thirdweb-dev/docs pull request #537
Opened 2023-03-30 23:04 UTC by MananTank

2023-03-30 23:21 UTC, jarrodwatts commented
Can we follow the structure of the other docs? 

h1 
explain what hook does
import and basic usage code block

h2 Usage
detailed codeblock

h2 Return Value
Explain what value is returned
typescript codeblock of what type is returned

2023-03-30 23:21 UTC, jarrodwatts requested changes
Left in comment

2023-03-30 23:25 UTC, jarrodwatts commented on docs/react/hooks/network/useNetwork.mdx
> +        const result = await switchNetwork(80001);
code doesn't work, await is not allowed here

2023-03-30 23:25 UTC, jarrodwatts commented on docs/react/hooks/network/useNetwork.mdx
> +    return <div> Wallet does not allow programmatic switching </div>;
weird spacing on these div texts

2023-03-30 23:26 UTC, jarrodwatts commented on docs/react/hooks/network/useNetwork.mdx
> +slug: /react.useNetwork
slug should be lowercase

2023-03-30 23:26 UTC, jarrodwatts commented on docs/react/hooks/network/useNetwork.mdx
> +  <summary> <code> data </code> </summary>
weird spacing and shouldn't be in code blocks

2023-03-30 23:27 UTC, jarrodwatts commented on docs/react/hooks/network/useNetwork.mdx
> +`Loading` is `true` when switching network using the `switchNetwork` function returned by the hook, and `false` otherwise.
shouldn't be capital `l` loading here

2023-04-02 17:58 UTC, MananTank commented
@jarrodwatts Please review the changes

2023-04-03 05:28 UTC, jarrodwatts approved these changes

2023-04-03 05:28 UTC, merged