Jw/guide redirects
thirdweb-dev/docs pull request #98
Opened 2022-06-14 23:45 UTC by jarrodwatts

2022-06-14 23:55 UTC, jarrodwatts commented
@nachoiacovino here are changes you suggested in discord

2022-06-15 19:02 UTC, jnsdls requested changes
redirects have to be carefully considered also if unsure never use permanent redirect

2022-06-15 19:02 UTC, jnsdls commented on vercel.json
> +      "permanent": true
we cannot use a permanent redirect with a *generated* destination, that destination can change with no knowledge on the docs side

2022-06-16 03:06 UTC, jarrodwatts commented on vercel.json
> +      "permanent": true
removed permanent from all three

2022-06-16 03:33 UTC, nachoiacovino commented on vercel.json
> +      "permanent": true
First two were fine, the third one was the problem because it was generated

2022-06-16 04:22 UTC, jarrodwatts commented on vercel.json
> +      "permanent": true
ok added the two back

2022-06-17 17:41 UTC, jnsdls approved these changes

2022-06-17 17:42 UTC, merged